# Generated by Django 3.2.9 on 2021-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='buyer_model',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='menufacture',
        ),
        migrations.AddField(
            model_name='staffuser',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
