# Generated by Django 3.2.9 on 2021-12-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211208_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='buyer_model',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='menufacture',
        ),
    ]
