# Generated by Django 3.2.9 on 2021-12-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinquiry',
            name='attachment_file',
        ),
        migrations.CreateModel(
            name='BuyerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('1', 'Open'), ('2', 'Close')], max_length=20, null=True)),
                ('buyerinq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerinquiry')),
            ],
        ),
    ]
