# Generated by Django 3.2.9 on 2021-12-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20211207_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinquiry',
            name='buyer_model',
        ),
        migrations.RemoveField(
            model_name='buyerinquiry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='buyerinquiry',
            name='menufacture',
        ),
    ]
