# Generated by Django 3.2.9 on 2021-12-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211209_1341'),
        ('buyer', '0003_auto_20211208_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Open'), ('2', 'Close')], max_length=20, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerMenufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menufacture_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Open'), ('2', 'Close')], max_length=20, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_list', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Open'), ('2', 'Close')], max_length=20, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Open'), ('2', 'Close')], max_length=20, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffuser')),
            ],
        ),
    ]
