# Generated by Django 3.2.9 on 2021-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyercategories_buyeremails_buyermenufactures_buyermodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinquiry',
            name='reference_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
