# Generated by Django 3.2.9 on 2021-12-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyerinquiry_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerinquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Received'), ('2', 'Sourcing'), ('3', 'Submitted'), ('4', 'Won'), ('5', 'Lost'), ('6', 'Close')], max_length=20, null=True),
        ),
    ]
