# Generated by Django 3.2.9 on 2021-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_alter_buyerinquiry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInquiryToVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(blank=True, max_length=20, null=True)),
                ('inquires', models.TextField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
