# Generated by Django 3.2.9 on 2021-12-17 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_buyerinquirytovendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinquiry',
            name='update_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
