# Generated by Django 3.2.9 on 2021-12-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_buyerinquiry_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinquiry',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
