# Generated by Django 3.2.9 on 2021-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_auto_20211217_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerinquirytovendor',
            name='no_of_vendor_send',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyerinquirytovendor',
            name='quotes_received',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
